// This file is auto-generated by `npm run db:codegen` once Postgres is running
// with the migrations applied. Run:
//   npm run db:up
//   npm run db:migrate
//   npm run db:codegen
//
// Placeholder below so the project type-checks before the real DB exists.

export interface DB {
  [key: string]: any;
}
